
import Database.DbConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author STUDENTS
 */
public class Register_form extends javax.swing.JFrame {


    /**
     * Creates new form Register_form
     */
    public Register_form() {
        initComponents();
         DbConnection db = new DbConnection();
        
      ResultSet rs =  db.getData("SELECT DISTINCT `religion` FROM religion");
      
        try {
            while(rs.next()){
                cmb_religion.addItem(rs.getString("religion"));
            } 
                 rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(Register_form.class.getName()).log(Level.SEVERE, null, ex);
        }
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_prf = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JLabel();
        lbl_dob = new javax.swing.JLabel();
        lbl_religion = new javax.swing.JLabel();
        lbl_caste = new javax.swing.JLabel();
        lbl_mthrtng = new javax.swing.JLabel();
        lbl_number = new javax.swing.JLabel();
        lbl_living = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        cmb_mpf = new javax.swing.JComboBox<>();
        txt_name = new javax.swing.JTextField();
        btn_male = new javax.swing.JRadioButton();
        btn_female = new javax.swing.JRadioButton();
        cmb_dd = new javax.swing.JComboBox<>();
        cmb_mm = new javax.swing.JComboBox<>();
        cmb_yy = new javax.swing.JComboBox<>();
        cmb_religion = new javax.swing.JComboBox<>();
        cmb_caste = new javax.swing.JComboBox<>();
        cmb_mt = new javax.swing.JComboBox<>();
        txt_number = new javax.swing.JTextField();
        cmb_livin = new javax.swing.JComboBox<>();
        txt_password = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        lbl_register = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        txt_dd = new javax.swing.JLabel();
        txt_mm = new javax.swing.JLabel();
        txt_yy = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_prf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_prf.setText("Matrimony profile for");
        lbl_prf.setName("lbl_prf"); // NOI18N

        lbl_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_name.setText("Name");

        lbl_gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_gender.setText("Gender");

        lbl_dob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_dob.setText("Date of birth");

        lbl_religion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_religion.setText("Religion");

        lbl_caste.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_caste.setText("Caste");

        lbl_mthrtng.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_mthrtng.setText("Mother tongue");

        lbl_number.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_number.setText("Mobile number");

        lbl_living.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_living.setText("Living in");

        lbl_password.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_password.setText("Login password");

        cmb_mpf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Myself", "Son", "Daughter", "Brother", "Sister", "Relative", "Friend" }));
        cmb_mpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_mpfActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn_male);
        btn_male.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_male.setText("Male");
        btn_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maleActionPerformed(evt);
            }
        });

        buttonGroup1.add(btn_female);
        btn_female.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_female.setText("Female");

        cmb_dd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cmb_dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ddActionPerformed(evt);
            }
        });

        cmb_mm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Agu", "Sep", "Nov", "Dec" }));

        cmb_yy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975" }));

        cmb_religion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_religionItemStateChanged(evt);
            }
        });
        cmb_religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_religionActionPerformed(evt);
            }
        });

        cmb_mt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Malayalam", "Hindi", "Tamil", " " }));

        cmb_livin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kerala", "Tamilnadu", "Mumbai", "UAE", "Karnataka" }));

        btn_register.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        lbl_register.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_register.setText("REGISTER FORM");
        lbl_register.setName("lbl_register"); // NOI18N

        btn_back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        txt_dd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_dd.setText("DD");

        txt_mm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_mm.setText("MM");

        txt_yy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_yy.setText("YY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_password)
                    .addComponent(lbl_number)
                    .addComponent(lbl_mthrtng)
                    .addComponent(lbl_caste)
                    .addComponent(lbl_religion)
                    .addComponent(lbl_dob)
                    .addComponent(lbl_living)
                    .addComponent(lbl_gender)
                    .addComponent(lbl_name)
                    .addComponent(lbl_prf))
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_dd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_mm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_yy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb_yy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_male)
                                .addGap(28, 28, 28)
                                .addComponent(btn_female)))
                        .addGap(0, 369, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_caste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_mpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txt_number, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmb_mt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmb_livin, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(lbl_register, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_register, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_mpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_prf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_name))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_male)
                    .addComponent(lbl_gender)
                    .addComponent(btn_female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_dob)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_religion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_yy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_dd)
                            .addComponent(txt_mm)
                            .addComponent(txt_yy)
                            .addComponent(cmb_dd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cmb_religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_caste, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmb_caste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_mt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(txt_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_mthrtng)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_number)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_living)
                            .addComponent(cmb_livin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_password))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_register)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_back)
                        .addGap(48, 48, 48))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_mpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_mpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_mpfActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
        String phone=txt_number.getText();
        String name=txt_name.getText();
        String mpf=(String) cmb_mpf.getSelectedItem();
        btn_male.setActionCommand("male");
        btn_female.setActionCommand("female");
        String gender=buttonGroup1.getSelection().getActionCommand();
        String day=(String) cmb_dd.getSelectedItem();
        String month=(String) cmb_mm.getSelectedItem();
        String year=(String) cmb_yy.getSelectedItem();
        String dob=day+"/"+month+"/"+year;
        String religion=(String) cmb_religion.getSelectedItem();
        String caste=(String) cmb_caste.getSelectedItem();
        String mt=(String) cmb_mt.getSelectedItem();
        String mb_no=txt_number.getText();
        String livin=(String) cmb_livin.getSelectedItem();
        String lg_password=txt_password.getText();
        try {
            Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/matrimony_db","root","");
            Statement stmt = connect.createStatement();
            String query = "INSERT INTO Register_form set mpf='"+mpf+"', name='"+name+"', gender='"+gender+"', dob='"+dob+"', religion='"+religion+"', caste='"+caste+"', mt='"+mt+"', mb_no='"+mb_no+"', livin='"+livin+"', lg_password='"+lg_password+"'";
            System.out.println(query);
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(rootPane,"Inserted");
        } catch (Exception e) {
            //e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
           
        }
                
    }//GEN-LAST:event_btn_registerActionPerformed

    private void cmb_religionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_religionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_religionActionPerformed

    private void cmb_religionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_religionItemStateChanged
        // TODO add your handling code here:
        String religion = cmb_religion.getSelectedItem().toString();
       // JOptionPane.showMessageDialog(null, religion);
       DbConnection db = new DbConnection();
      ResultSet rs =  db.getData("SELECT caste from religion where religion = '"+religion+"'");
      cmb_caste.removeAllItems();
        try {
            while(rs.next()){
              cmb_caste.addItem(rs.getString("caste"));
            } 
        } catch (SQLException ex) {
            Logger.getLogger(Register_form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmb_religionItemStateChanged

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:`
        this.setVisible(false);
        Register_form r=new Register_form();
        r.setVisible(true);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        welcome w=new welcome();
        w.setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maleActionPerformed
        // TODO add your handling code here:
      btn_male.setActionCommand("male");
      btn_female.setActionCommand("female");
      String g=buttonGroup1.getSelection().getActionCommand();
      
    }//GEN-LAST:event_btn_maleActionPerformed

    private void cmb_ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_ddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_clear;
    private javax.swing.JRadioButton btn_female;
    private javax.swing.JRadioButton btn_male;
    private javax.swing.JButton btn_register;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_caste;
    private javax.swing.JComboBox<String> cmb_dd;
    private javax.swing.JComboBox<String> cmb_livin;
    private javax.swing.JComboBox<String> cmb_mm;
    private javax.swing.JComboBox<String> cmb_mpf;
    private javax.swing.JComboBox<String> cmb_mt;
    private javax.swing.JComboBox<String> cmb_religion;
    private javax.swing.JComboBox<String> cmb_yy;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel lbl_caste;
    private javax.swing.JLabel lbl_dob;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_living;
    private javax.swing.JLabel lbl_mthrtng;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_number;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_prf;
    private javax.swing.JLabel lbl_register;
    private javax.swing.JLabel lbl_religion;
    private javax.swing.JLabel txt_dd;
    private javax.swing.JLabel txt_mm;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_number;
    private javax.swing.JTextField txt_password;
    private javax.swing.JLabel txt_yy;
    // End of variables declaration//GEN-END:variables
}
